// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // CONFIGURACIÓN WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9AnOHCBlyKJ98jNI_5r1y-xfAcJYLgI',
    appId: '1:360714035813:web:ba82060633b2f57b629c8c',
    messagingSenderId: '360714035813',
    projectId: 'playas-rd-2b475',
    authDomain: 'playas-rd-2b475.firebaseapp.com',
    storageBucket: 'playas-rd-2b475.firebasestorage.app',
    measurementId: 'G-451PZ22SF7',
  );

  // CONFIGURACIÓN ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFS0POsHWn9azaDIAviZM8FlUSjf8_fVs',
    appId: '1:360714035813:android:b257f7be5740162e629c8c',
    messagingSenderId: '360714035813',
    projectId: 'playas-rd-2b475',
    storageBucket: 'playas-rd-2b475.firebasestorage.app',
  );

  // CONFIGURACIÓN iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUfP7yerqjzXPMSxGU4I50OpQATcrqQ4',
    appId: '1:360714035813:ios:e7b023b9692d3d09629c8c',
    messagingSenderId: '360714035813',
    projectId: 'playas-rd-2b475',
    storageBucket: 'playas-rd-2b475.firebasestorage.app',
    iosClientId:
        '360714035813-j1q7j0elbuep49uurma34kkofh9v27i5.apps.googleusercontent.com',
    iosBundleId: 'com.playasrd.playasrd',
  );

  // CONFIGURACIÓN macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUfP7yerqjzXPMSxGU4I50OpQATcrqQ4',
    appId: '1:360714035813:ios:e7b023b9692d3d09629c8c',
    messagingSenderId: '360714035813',
    projectId: 'playas-rd-2b475',
    storageBucket: 'playas-rd-2b475.firebasestorage.app',
    iosClientId:
        '360714035813-j1q7j0elbuep49uurma34kkofh9v27i5.apps.googleusercontent.com',
    iosBundleId: 'com.playasrd.playasrd',
  );

  // CONFIGURACIÓN Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9AnOHCBlyKJ98jNI_5r1y-xfAcJYLgI',
    appId: '1:360714035813:web:ba82060633b2f57b629c8c',
    messagingSenderId: '360714035813',
    projectId: 'playas-rd-2b475',
    authDomain: 'playas-rd-2b475.firebaseapp.com',
    storageBucket: 'playas-rd-2b475.firebasestorage.app',
    measurementId: 'G-451PZ22SF7',
  );
}
